name: Meraki-Build
# Cancel in progress runs if a new one is started
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linting_check:
    runs-on: ubuntu-latest
    # Don't allow runs longer than 20 minutes
    timeout-minutes: 20
    strategy:
      matrix:
        node-version: [ 16 ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Cache all node_modules
      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
      - name: Install npm modules
        run: npm ci

      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Run eslint
        run: |
          echo `Modified files are ${{ steps.files.outputs.all }}`
          npx eslint ${{ steps.files.outputs.all }}
      - name: Build app
        run: npm run build
